### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [peter-tank/luci-app-ssr-plus#1]
openwrt master
除了PDNSD 其他都无法运行
DNSCrypt模式下报错
![QQ截图20191202140425](https://user-images.githubusercontent.com/26851715/69934410-ca892d80-150c-11ea-86a7-a0e99fe7d61e.png)

**Comment by peter-tank** [comment]
wget版本不同，不认这个重试下载的次数设定。
订阅更新也会有问题，可能装下wget可以自己解决。自带的好像一般都不能从https网址去下载，`wget-ssl`看有没有这个命令。

3个文件影响`grep "wget .*-t" -rn`
```
root/etc/init.d/dnscrypt-proxy:382:        wget -q --no-check-certificate -t 3 -T 30 -O "$tmpf" "$cdl"
root/usr/share/shadowsocksr/update.sh:3:chnroute_data=$(wget -O- -t 3 -T 3 http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest)
root/usr/share/dnscrypt-proxy/uci_handle_exec.sh:46:        wget -q --no-check-certificate -t 3 -T 30 -O "$tmpf" "$cdl"
```

**Comment by fuqiang03** [comment]
好的

**Comment by peter-tank** [comment]
不知道你刷的什么固件，这个ssr是从lede里改过来的，如果你不是用的那个固件，会遇到不少问题至少需要：dnsmasq full， iptables mod，ipset。

**Comment by fuqiang03** [comment]
lede 和新版的openwrt luci不兼容的 依赖没有问题
但是老版本的可以使用

**Comment by fuqiang03** [comment]
lede 和新版的openwrt luci不兼容的 依赖没有问题
但是老版本的可以使用

**Comment by fuqiang03** [comment]
请问你用的是openwrt 那个分支的

**Comment by peter-tank** [comment]
如果不是想玩下DNSCrypt，建议你用[这里的](https://github.com/Lienol/openwrt-package/tree/master/lienol)，写得挺工整。
其实是应该把DNSCrypt独立打包也来的，我是懒了不想整。

**Comment by fuqiang03** [comment]
好的

**Comment by fuqiang03** [comment]
大部分源码对open的新代码支持的不是很好 不过我喜欢弄新的

**Comment by peter-tank** [comment]
用的别人编译的[LEDE旧固件](https://github.com/coolsnowwolf/lede)

**Comment by fuqiang03** [comment]
lean的固件不旧 旧是luci 没有更新
我也是从lean里面提取一些 ipk 而已 
我自己还是官方的源码 这样就有ipk不兼容的情况  只能自己慢慢弄

**Comment by peter-tank** [comment]
我也想只是用官版，规划好点，可玩性也更强。各种魔改要装强制的依赖太多 ...
你有改好的可以丢个链接在这里，我也好撿。
