### ISSUE TITLE
Hi, how do i use this in official OpenWRT?

### ISSUE THREAD

**Issue by chchia** [peter-tank/luci-app-ssr-plus#2]
i trying to compile this in the official OpenWRT, with required dependency, however i cannot get SSR-Plus to start correctly.

i have copied the required dependencies including pdnsd-alt, shadowsocks-libev-alt etc. i dont have problem for compiling, it just that SSR Plus just cant start the client.

thank you.

**Comment by peter-tank** [comment]
There needs extra FULLCONENAT patched for kernel, and this repo meets connection refused issue not fixed yet.(iptables scripts need rewrite to compliant with).
So, don't use it as TPROXY client.

----
Recommend you try [luci-app-passwall](https://github.com/Lienol/openwrt-package)
