### ISSUE TITLE
缺少依赖

### ISSUE THREAD

**Issue by deansay** [peter-tank/luci-app-ssr-plus#3]
root@X-WRT:/mnt/sda1# opkg install luci-app-ssr-plus_7-2_all.ipk 
Installing luci-app-ssr-plus (7-2) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 *  tcping
 *  pdnsd-alt
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.

**Comment by peter-tank** [comment]
Follow release notes. If your router matches my builds, just download the depends from github Action.
Or `opkg install -nodep xxx ipk` for a preview.
-----
Depends download: [github actions](https://github.com/peter-tank/openwrt/actions/runs/38539156)/Artifacts/customed_packages
